// Generated by ts-to-zod
import { z } from "zod";

export const outfitSchema = z.object({
  head: z.array(
    z.object({
      price: z.number(),
      name: z.string(),
      urls: z.array(z.string()),
      color: z.string(),
      reasoning: z.string(),
      description: z.string(),
      type: z.string(),
      category: z.union([
        z.literal("clothing"),
        z.literal("accessory"),
        z.literal("shoes"),
      ]),
    }),
  ),
  torso: z.array(
    z.object({
      price: z.number(),
      name: z.string(),
      urls: z.array(z.string()),
      color: z.string(),
      reasoning: z.string(),
      description: z.string(),
      type: z.string(),
      category: z.union([
        z.literal("clothing"),
        z.literal("accessory"),
        z.literal("shoes"),
      ]),
    }),
  ),
  legs: z.array(
    z.object({
      price: z.number(),
      name: z.string(),
      urls: z.array(z.string()),
      color: z.string(),
      reasoning: z.string(),
      description: z.string(),
      type: z.string(),
      category: z.union([
        z.literal("clothing"),
        z.literal("accessory"),
        z.literal("shoes"),
      ]),
    }),
  ),
  feet: z.array(
    z.object({
      price: z.number(),
      name: z.string(),
      urls: z.array(z.string()),
      color: z.string(),
      reasoning: z.string(),
      description: z.string(),
      type: z.string(),
      category: z.union([
        z.literal("clothing"),
        z.literal("accessory"),
        z.literal("shoes"),
      ]),
    }),
  ),
});
